curl -i -X POST http://localhost:3500/api/users/newGame -d '' -H "Content-Type: application/json"
curl -i -X POST http://localhost:3500/api/users/newGame -d '' -H "Content-Type: application/json"
curl -i -X POST http://localhost:3500/api/users/newGame -d '' -H "Content-Type: application/json"
curl -i -X POST http://localhost:3500/api/users/newGame -d '' -H "Content-Type: application/json"
curl -i -X POST http://localhost:3500/api/users/newGame -d '' -H "Content-Type: application/json"
curl -i -X POST http://localhost:3500/api/users/newGame -d '' -H "Content-Type: application/json"
curl -i -X POST http://localhost:3500/api/users/newGame -d '' -H "Content-Type: application/json"
curl -i -X POST http://localhost:3500/api/users/newGame -d '' -H "Content-Type: application/json"
curl -i -X POST http://localhost:3500/api/users/newGame -d '' -H "Content-Type: application/json"
curl -i -X POST http://localhost:3500/api/users/newGame -d '' -H "Content-Type: application/json"
curl -i -X POST http://localhost:3500/api/users/newGame -d '' -H "Content-Type: application/json"
curl -i -X POST http://localhost:3500/api/users/newGame -d '' -H "Content-Type: application/json"
curl -i -X POST http://localhost:3500/api/users/newGame -d '' -H "Content-Type: application/json"
curl -i -X POST http://localhost:3500/api/users/newGame -d '' -H "Content-Type: application/json"
curl -i -X POST http://localhost:3500/api/users/newGame -d '' -H "Content-Type: application/json"

