curl -i -X POST http://localhost:3500/api/game/newGame -d '' -H "Content-Type: application/json"
curl -i -X POST http://localhost:3500/api/game/newGame -d '' -H "Content-Type: application/json"
curl -i -X POST http://localhost:3500/api/game/newGame -d '' -H "Content-Type: application/json"
curl -i -X POST http://localhost:3500/api/game/newGame -d '' -H "Content-Type: application/json"
curl -i -X POST http://localhost:3500/api/game/newGame -d '' -H "Content-Type: application/json"
curl -i -X POST http://localhost:3500/api/game/newGame -d '' -H "Content-Type: application/json"
curl -i -X POST http://localhost:3500/api/game/newGame -d '' -H "Content-Type: application/json"
curl -i -X POST http://localhost:3500/api/game/newGame -d '' -H "Content-Type: application/json"
curl -i -X POST http://localhost:3500/api/game/newGame -d '' -H "Content-Type: application/json"
curl -i -X POST http://localhost:3500/api/game/newGame -d '' -H "Content-Type: application/json"
curl -i -X POST http://localhost:3500/api/game/newGame -d '' -H "Content-Type: application/json"
curl -i -X POST http://localhost:3500/api/game/newGame -d '' -H "Content-Type: application/json"
curl -i -X POST http://localhost:3500/api/game/newGame -d '' -H "Content-Type: application/json"
curl -i -X POST http://localhost:3500/api/game/newGame -d '' -H "Content-Type: application/json"
curl -i -X POST http://localhost:3500/api/game/newGame -d '' -H "Content-Type: application/json"

