curl -i -X POST http://localhost:8080/api/users/newGame -d '' -H "Content-Type: application/json"
curl -i -X POST http://localhost:8080/api/users/newGame -d '' -H "Content-Type: application/json"
curl -i -X POST http://localhost:8080/api/users/newGame -d '' -H "Content-Type: application/json"
curl -i -X POST http://localhost:8080/api/users/newGame -d '' -H "Content-Type: application/json"
curl -i -X POST http://localhost:8080/api/users/newGame -d '' -H "Content-Type: application/json"
curl -i -X POST http://localhost:8080/api/users/newGame -d '' -H "Content-Type: application/json"
curl -i -X POST http://localhost:8080/api/users/newGame -d '' -H "Content-Type: application/json"
curl -i -X POST http://localhost:8080/api/users/newGame -d '' -H "Content-Type: application/json"
curl -i -X POST http://localhost:8080/api/users/newGame -d '' -H "Content-Type: application/json"
curl -i -X POST http://localhost:8080/api/users/newGame -d '' -H "Content-Type: application/json"
curl -i -X POST http://localhost:8080/api/users/newGame -d '' -H "Content-Type: application/json"
curl -i -X POST http://localhost:8080/api/users/newGame -d '' -H "Content-Type: application/json"
curl -i -X POST http://localhost:8080/api/users/newGame -d '' -H "Content-Type: application/json"
curl -i -X POST http://localhost:8080/api/users/newGame -d '' -H "Content-Type: application/json"
curl -i -X POST http://localhost:8080/api/users/newGame -d '' -H "Content-Type: application/json"

