import { Server, Socket } from 'socket.io';
import { GameService } from './game.service';
import { Status, GamePatron, Player } from './game.types';
export declare class GameAlgo {
    private readonly gameService;
    readonly server: Server;
    readonly roomID: string;
    private status;
    readonly gameModel: GamePatron;
    private player1;
    private player2;
    private interval;
    private gameData;
    private watchers;
    private readonly internalEvents;
    constructor(gameService: GameService, server: Server, roomID: string);
    launchGame(): Promise<string>;
    private startGame;
    private computeGame;
    private countDown;
    initPlayer1(player: Player): void;
    initPlayer2(player: Player): void;
    getStatus(): Status;
    getPlayerID(player1ou2: number): string;
    playerChangeSocket(playerSocket: Socket, socketID: string, player1ou2: number): void;
    addWatcherSocketID(newWatcherSocketId: string): void;
    private initGameData;
    private rotateGameData;
    private playersTimeout;
}
